### ISSUE TITLE
Permit pasting of paths from clipboard

### ISSUE THREAD

**Issue by raumzeitfalle** [Oliver-Loeffler/FXFileChooser#32]
One strong feature of system file choosers is, that they allow to paste full paths from clipboard into the dialog and to continue with the pasted path.

* The dialog then should indicate, if the pasted path is incorrect or does not exists.
* If the pasted path is just a directory, the dialog should change the directory location.
* If the pasted path is a file, the dialog should also change to the directory location.

**Comment by Oliver-Loeffler** [comment]
Now a path can either be typed into the filter text field or pasted.
When return key is pressed, then the FileChooser will attempt to switch into the new directory (if it really exists). When a path is pasted, which points to a file, then the FileChooser will attempt to switch to the appropriate parent directory.

- [ ]  Indication if entered path is valid does not yet exist (open)
- [ ]  If the pasted path is just a directory, the dialog should change the directory locatio
- [ ] If the pasted path is a file, the dialog should also change to the directory location.

Closed with e1ab85b75926082ae003affd85509e50f988f637.
