### ISSUE TITLE
Allow to configure window modality 

### ISSUE THREAD

**Issue by Oliver-Loeffler** [Oliver-Loeffler/FXFileChooser#36]
Currently FXFileChooser is always application modal. There are cases where different modality is needed.

**Comment by Hugolarson** [comment]
Hello,
Thank you for this product.
I would like to open a FXFileChooser in non modal manner like JFoenix JFXDialog.
Intention is to use it in JPro where the UI thread cannot be blocked.

Does this solving this issue achieve it?

**Comment by Oliver-Loeffler** [comment]
Hello, well there will be a new version latest within next week, where modality will be configurable. Currently the default is `Modality.APPLICATION_MODAL`. Modality does not block the UI thread, it configures if underlaying windows (e.g. the main application window) are focusable and selectable. For case of `Modality.APPLICATION_MODAL`, the parent window of the dialog is not accessible as long the FXFileChooserStage is visible. After closing the FXFileChooserStage, the parent window again becomes accessible.

To configure modality I plan to either modify the `FXFileChooserStage.create()` method or create some kind of a builder, a fluent API.

```java
    @Override
    public void start(Stage primaryStage) throws Exception {
        Button button = new Button("Show File Chooser");
        FXFileChooserStage fc = FXFileChooserStage.create(Skin.DARK);
        button.setOnAction(evt-> fc.showOpenDialog(primaryStage).ifPresent(this::showSelection));

        Scene scene = new Scene(button);
        primaryStage.setScene(scene);
        primaryStage.setTitle("Demo");
        primaryStage.show();
    }
```

Have you already tried FXFileChooser in JPro? I will look into it.

The current version creates a 2nd window (stage) additionally to the main application stage.
If in JPro any errors occurr due to JavaFX thread blocking, this is a bug and I would have to dig into. However, I will test JPro anyways - never tried it yet.

If the 2nd stage, the separate FXFleChooser window, causes trouble, I would have to test this and figure out how to integrate this use case. 

Which Java and JavaFX version do you run?

**Comment by Hugolarson** [comment]
Hello,
I use Java 8 and have not actually tried with JPro and for some reason thought FXFileChooser is always Modal.
And yes FXFileChooser will not allow me to browse files on client I have learned.
Thank you for the explanation.

**Comment by Oliver-Loeffler** [comment]
Configuration of modality for `FXFileChooserStage` is already working. This can be achieved by calling `Stage.initModality(...)` method like:

```java
PathFilter[] filters = new PathFilter[] {all, xml, xlsx, na0, txt, exe, combined};
FXFileChooserStage fileChooserStage = FXFileChooserStage.create(Skin.DARK, local, filters);
fileChooserStage.initModality(Modality.NONE);

Button button = new Button("FXFileChooserStage (Skin.DARK, Modality.NONE)");
button.setOnAction(e -> {
        if (fileChooserStage.isShowing()) {
            e.consume();  // JavaFX will otherwise complain if stage is already showing
            return;
        }
        Optional<Path> selection = fcDarkNonModal.showOpenDialog(primaryStage);
        // handle selection here
    });

```

Alternatively one can make use of the class `FileChooser` which can be embedded as a control like a button into any other view or even in FXML. Modality is not known as a concept to the `FileChooser` class itself. It only plays a role when placed in a dialog or separate stage.
